version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: fthi/php-app
    environment:
      WWWUSERID: 1000
    volumes:
      - .:/var/www/html
    ports:
      - "8181:8080"
    networks:
      - ftnet
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
    networks:
      - ftnet
  db:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
        MYSQL_DATABASE: coinnik
        MYSQL_ROOT_PASSWORD: 123123
        MYSQL_USER: farzin
        MYSQL_PASSWORD: 123123
    networks:
      - ftnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_USER: farzin
      MYSQL_PASSWORD: 123123
    ports:
      - 8282:80
    networks:
      - ftnet
    volumes:
      - phpmyadmindata:/phpmyadmindata
networks:
  ftnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
  phpmyadmindata:
    driver: "local"
