version: '3.1'
services:
  app:
    build:
      context: "${DOCKERFILE_PATH}"
      dockerfile: Dockerfile
    image: laravel/php-app
    environment:
      WWWUSERID: "${WWWUSERID}" 
    volumes:
      - "${APP_PATH}:/var/www/html"
    ports:
      - "${APP_PORT}:8080"
    networks:
      - laravel
  db:
    image: mariadb
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_USER: "${DB_USER}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - laravel
    volumes:
      - phpmyadmindata:/phpmyadmindata
networks:
  laravel:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
  phpmyadmindata:
    driver: "local"
